### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Aziiimm** [notprowler/quickbid#22]
# To-Do List

## 1. Listings Page
- [x] Create API route to load data into the listings page. *(mid shouldnt be that bad tbh)*
- [x] Add `category` as an attribute for products in the database. *(easy af)* - look at categories in main branch. /listings.tsx
## 2. Profile Page
- [x] Connect Supabase authentication to the profile page. *(easy enough)*
- [x] #28
  - Users can favorite an item on the product page. *(mid but could be annoying w typescript smh)*
  *Implement an endpoint to store and retrieve user favorites*
  - Display favorited items in the "Favorites" section of the profile page.

## 3. User Authentication
- [ ] Restrict unauthenticated users from interacting with listings: *(easy)*
*Redirect unauthenticated users to the login page.*

## 4. Transactions
- [x] Implement transaction logic to change values in the db: *(mid)*
- [x] Transactions API endpoint
*Make sure buyer balance is valid before deducting funds* - FRONTEND CHECKS only then SENDS request
  - Deduct money from the buyer.
  - Add money to the seller. 

## 5. Landing Page
- [x] Adjust the landing page: *(easy af but could be annoying with typescript if we choose to keep the searchbar)*
  - Either remove the search bar and redesign the layout.
  - Or pass the search bar input to the listings page and apply the search logic there.

## 6. Bidding System
- [ ] Implement bidding feature + logic *(HARD)*:
  - Include timers for bids.
  *need to do some research on how this can be done*
  - Add confirmation for winning or losing a bid.
  *need realtime updates, and show outcome in the cart page/profile page?. need to research how we can do this*

## 7. Create Listing
- [x] Implement logic for creating a new listing:
  - Save listings to the database. *(mid and annoying)*
  *need to make it a form basically. make sure it aligns w every attribute needed shown in the db schema*
- [x] Handle images upload using Supabase Storage, integrate with listings table, and other API changes
## 8. Roles Implementation
-[ ] IF WE NEED MULTIPLE IMAGES - Implement image scrolling in both listings page and each individual listing page.
- [ ] Logic for roles, V,  U, S
## 9. SuperUser View to ban/demote users
- [ ] logic for that 

## 10. 
- [ ] API Endpoint to get Live Active bids for a user.

## 11.

1) Before starting, email the professor if this chatbot counts as the valid bonus / creative feature
2) Main task - needs to give u info about current active listings - any thing u like about in it.
3) Model - openai API 4o mini 
- Feed it data from listings table - to begin with
- Get the chatbot backend sending back responses 

## 12. 
[ ] Fully fledged reviews and comments functionality, profile page

# 13.
[ ] Application feature, which must be approved by super user in their menu *(should be relatively easy tbh)*
## DO THIS AFTER ROLES HAVE BEEN IMPLEMENTED

**Comment by notprowler** [comment]
I got 1 and 7 for now

**Comment by Aziiimm** [comment]
I got 4 and 6

**Comment by IvanC112** [comment]
All transactions in Profile Page and connect to review/comment component

**Comment by ATMmonitor667** [comment]
Got the Open_AI ai connected for 11 and set up the backend

**Comment by Aziiimm** [comment]
1 . Connected listings page to backend + got filters feature working with it

![image](https://github.com/user-attachments/assets/58977580-0d67-4479-8682-aea2367f9f16)

2. Got product page to work accordingly 

![image](https://github.com/user-attachments/assets/0855a49a-1ffd-4d8e-a6ec-1126e2400775)

![image](https://github.com/user-attachments/assets/589922cf-9937-4071-98da-2b66b4b218c5)
